### ISSUE TITLE
500 error respon

### ISSUE THREAD

**Issue by reactmorelab** [josephdenne/PHP-URL-Shortener#1]
i dont know where mistake no log error in my folder 

after setting config i push to my host , and then open in my browser but link 500 error respon

**Comment by emesare** [comment]
he forgot to include .htaccess go to this [repo](https://github.com/briancray/PHP-URL-Shortener), grab the **rename.htaccess** then rename it to _.htaccess_ and your good to go. if you still get error do what it says inside the _.htaccess_ (comments)

**Comment by reactmorelab** [comment]
thanks
